# generated by configure / remove this line to disable regeneration
prefix="/Users/mstrout/SVNWorkDirs/IEGenProject/trunk/IEGen/src/libs/cloog/installed"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/Users/mstrout/SVNWorkDirs/IEGenProject/trunk/IEGen/src/libs/cloog/isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/Users/mstrout/SVNWorkDirs/IEGenProject/trunk/IEGen/src/libs/cloog/isl/./include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.09"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "-L/Users/mstrout/SVNWorkDirs/IEGenProject/trunk/IEGen/src/libs/cloog/../gmp-5.0.5/installed/lib" "-lisl -lgmp"
:
;; --cflags) echo -I${includedir} "-I/Users/mstrout/SVNWorkDirs/IEGenProject/trunk/IEGen/src/libs/cloog/../gmp-5.0.5/installed/include"
:
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
