name: build/test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    steps:
    - name: Complete flex installation
      run: sudo apt-get install libfl-dev
    - uses: actions/checkout@v2
    - name: set TERM
      run: echo "TERM=xterm-256color" >> $GITHUB_ENV
    - name: build main project
      run: make
    - name: build tutorial examples
      run: make tutorial
    - name: run tests
      run: make test
    - run: ./build/bin/tutorial/append_computation_example
    - run: ./build/bin/tutorial/computation_example
    - run: ./build/bin/tutorial/geoac_codegen_driver
    - run: ./build/bin/tutorial/macro_testing
    - run: ./build/bin/tutorial/manual_graph_testing
    - run: ./build/bin/tutorial/miniFluxDiv_codegen_driver
    - run: ./build/bin/tutorial/sparse_format_example
